### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by bwolsey** [shamanskyh/homebridge-blinking-switch#1]
Hello and thanks for the plugin.
I like the idea of a single switch which I can use in a security automation which flashes a number of my lights throughout the house if the burglar alarm is tripped.  I've Installed and tried to make a switch and the switch shows up in my system, but it doesn't flash anything.  After looking at your [test]/[mocks]/scenes.json file, I've edited my advanced section in the configuration section to look like the below.  I've tried just #'s for the lights like your file, the stated name and the Serial Number (listed in the switch properties), but nothing I've tried has worked.  Any help will be Greatly Appreciated.

Thanks

{
    "accessories": [
        {
            "id": "Alarm_Flashing",
            "name": "Alarm Flashing",
            "lights": [
                "Family Room Lamps",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7"
            ],
            "Active": "true",
            "accessory": "BlinkingSwitch",
            "plugin_map": {
                "plugin_name": "homebridge-blinking-switch"
            }
        }
    ]
}

**Comment by shamanskyh** [comment]
Hi @bwolsey, sorry you’re having trouble getting the plugin to work. The tests/mocks/scenes file you found is a mistake and shouldn’t be there.

I should clarify that this plug-in does not blink any lights without a HomeKit automation associated with it, since it doesn’t have access to any lights on its own. To use this, you need to observe the “Status Active” property of the switch — one automation that triggers when status active changes to on, and another automation that triggers when status active changes to off. Don’t trigger your automations based on the switch itself, since that’s only used to say whether the blink should be enabled or disabled.

Please note that the built-in Apple Home app does not have support for triggering automations based on the Status Active property, so you’ll have to use another HomeKit app like Home+ or Eve for the initial set up.

If you’re able to set up automations and you’re still not able to get it to work, let me know and I can try to help you debug further.

**Comment by bwolsey** [comment]
Hello @shamanskyh,
I appreciate your response.  I've now deleted my first attempts and recreated a single switch in the plugin.  I do have the Eve App, but after spending 20 mins or so trying to figure out what Automations to create, I really cannot picture what the 2 automations are.  

To me, it sounds like you are saying the 2 automations I need to create are:
1. When Trigger X happens AND if the "Status Active" field of the switch created in the Blinking Switch plugin is set to "Active", then turn on light Y (and as many others as desired).  
2. When Trigger X happens AND if the "Status Active" field of the switch created in Blinking switch plugin is set to "Active", then turn off light Y (and as many others as desired).  

If that is correct, then this switch is just a dummy switch and has no logic behind it (and the two automations would just create a loop fighting with one another and potentially melt down my HomeKit controller/hub).  I don't believe that's correct since in your update to version 1.1.0, you stated that it "Increases the default blink time from 30 seconds to 300 seconds".  This means you've built logic into the switch and therefore, my 2 automations above cannot be right.  

Any suggestions?  And Thanks for your time.

**Comment by shamanskyh** [comment]
Sure, happy to help. The “Status Active” property of the switch is itself the trigger. When that property changes, you’ll activate a scene. Turning on the switch itself causes the “Status Active” property to oscillate back and forth between “true” and “false” at the frequency that you set in the config. This allows you to blink the lights on and off when the switch is on, and stop the blinking by turning the switch off.

I’ve attached the two automations I use to blink the lights on my deck. When I turn the switch itself on, the switch’s “Status Active” property changes to true, which triggers the first automation and turns the lights on. 10 seconds later, the switch’s “Status Active” property becomes false, which triggers the second automation and turns the lights off. We repeat this until the switch itself is turned off — when that happens then the timer stops and we immediately set “Status Active” to false one last time if that’s not the current state.

Let me know if this makes sense to you or if you’re still stuck and I’m happy to answer more questions. I’ll try to improve the README that includes an example like this if it’s helpful to you.

![4A766C9C-3C01-49D7-AE06-95B1E24F638D](https://user-images.githubusercontent.com/2146675/160981184-c0988424-c8af-4240-a121-6a34e99d7264.png)
![E137FBDA-DAFC-4EB5-8AE0-020DB08E5379](https://user-images.githubusercontent.com/2146675/160981189-bd233c62-4680-48f3-98c1-9173c5186e0a.png)

**Comment by bwolsey** [comment]
That was very helpful @shamanskyh.  I now have it working, but the duration is oscillating every 50 seconds.  Where do I modify the variable?  I know it says in the Config above, but my config just has this.

{
    "accessories": [
        {
            "name": "Alarm Flashing",
            "accessory": "BlinkingSwitch",
            "plugin_map": {
                "plugin_name": "homebridge-blinking-switch"
            }
        }
    ]
}

**Comment by shamanskyh** [comment]
Hi @bwolsey — the duration (frequency) is actually something that’s configured in HomeKit and not config file. To modify the duration, just adjust the “Set Duration” property of the switch. Please note that the default Home app may not show this property, so you may have to adjust it in the Home+ or Eve apps.

![727AB945-39B0-4251-9808-29E11C260691](https://user-images.githubusercontent.com/2146675/161394089-7205703e-a948-4c2a-b0a9-68e61b9cd67b.jpeg)

**Comment by bwolsey** [comment]
Thank you!!!  I’ve now got it working 100% and I truly appreciate you taking your personal time to help me get it working. If you decide to update your README files, the only thing outside what you sent which I ended up figuring out was that the eve app calls Automations Rules. Once I realized that, I was able to make the two automations. 

All that said, unfortunately this will not help me. My desired use case for this was to blink/flash the lights in my home when the burglar alarm was triggered after dark. My thought is that if they were blinking on/off every .5 - 2 seconds, it would be annoying/disorientating to a burglar. Regarding the time between states, I would pick a duration based on how responsive my personal switches are.  

Anyway, since the lowest duration in the switch settings is 10 seconds, and that’s not exactly disorientating, it doesn’t fit my needs. 

If you end up seeing a way to accomplish what I am trying to use it for and update the plug-in, that would be Awesome. But please know that I DO NOT expect that, it would just be cool and I would definitely appreciate it.  

Thanks again for your time and help getting it working.
